title: Allan's Portfolio
description: I am a Computer Science student a concentration in Cybersecurity and Information Assurance. I am driven by a passion for learning and professional growth, seeking internship opportunities to apply my skills, gain industry experience, and build a successful career in the Technology and Cybersecurity field.
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
